"""Zero-authority Brain research infrastructure.

Nothing in ``services.brain`` has execution, risk, position-management,
certification, or broker-submission authority.
"""

from .analyzer_registry_v1 import (
    ANALYZER_CATEGORIES,
    RUNTIME_ROLES,
    SOURCE_FAMILIES,
    SUPPORTED_MARKETS,
    AnalyzerDescriptorV1,
    AnalyzerRegistryV1,
    DEFAULT_ANALYZER_REGISTRY_V1,
)
from .market_snapshot_v1 import (
    MarketSnapshotV1,
    build_market_snapshot_v1,
)
from .snapshot_persistence_v1 import (
    SNAPSHOT_RECORD_SCHEMA_V1,
    SnapshotIntegrityError,
    SnapshotPersistenceConflictError,
    SnapshotPersistenceError,
    SnapshotRecordDecodeError,
    SnapshotReplayError,
    SnapshotSchemaError,
    load_snapshot_record_v1,
    persist_snapshot_record_v1,
    replay_snapshot_record_v1,
    serialize_snapshot_record_v1,
    snapshot_record_v1,
)
from .source_adapters_v1 import (
    IndexBreadthSourceV1,
    IndexNewsSourceV1,
    IndexOptionChainSourceV1,
    IndexPremarketSourceV1,
    IndexTechnicalSourceV1,
    McxEventRiskSourceV1,
    McxNativeSourceV1,
    adapt_index_breadth_v1,
    adapt_index_news_v1,
    adapt_index_option_chain_v1,
    adapt_index_premarket_v1,
    adapt_index_technical_v1,
    adapt_mcx_event_risk_v1,
    adapt_mcx_native_v1,
)

__all__ = [
    "ANALYZER_CATEGORIES",
    "RUNTIME_ROLES",
    "SOURCE_FAMILIES",
    "SUPPORTED_MARKETS",
    "AnalyzerDescriptorV1",
    "AnalyzerRegistryV1",
    "DEFAULT_ANALYZER_REGISTRY_V1",
    "MarketSnapshotV1",
    "build_market_snapshot_v1",
    "SNAPSHOT_RECORD_SCHEMA_V1",
    "SnapshotIntegrityError",
    "SnapshotPersistenceConflictError",
    "SnapshotPersistenceError",
    "SnapshotRecordDecodeError",
    "SnapshotReplayError",
    "SnapshotSchemaError",
    "load_snapshot_record_v1",
    "persist_snapshot_record_v1",
    "replay_snapshot_record_v1",
    "serialize_snapshot_record_v1",
    "snapshot_record_v1",
    "IndexBreadthSourceV1",
    "IndexNewsSourceV1",
    "IndexOptionChainSourceV1",
    "IndexPremarketSourceV1",
    "IndexTechnicalSourceV1",
    "McxEventRiskSourceV1",
    "McxNativeSourceV1",
    "adapt_index_breadth_v1",
    "adapt_index_news_v1",
    "adapt_index_option_chain_v1",
    "adapt_index_premarket_v1",
    "adapt_index_technical_v1",
    "adapt_mcx_event_risk_v1",
    "adapt_mcx_native_v1",
]