# trading_bot/core/constants.py
# Complete constants definition

from enum import Enum, auto

class MarketState(Enum):
    BOOT = "BOOT"
    CONFIG_VALIDATION = "CONFIG_VALIDATION"
    PROVIDER_VALIDATION = "PROVIDER_VALIDATION"
    MARKET_CALENDAR_VALIDATION = "MARKET_CALENDAR_VALIDATION"
    RECONCILIATION = "RECONCILIATION"
    PRE_MARKET = "PRE_MARKET"
    WEBSOCKET_READY = "WEBSOCKET_READY"
    MARKET_OPEN = "MARKET_OPEN"
    OBSERVING = "OBSERVING"
    SIGNAL_DETECTED = "SIGNAL_DETECTED"
    SIGNAL_VALIDATED = "SIGNAL_VALIDATED"
    STRIKE_SELECTED = "STRIKE_SELECTED"
    OPTION_VALIDATED = "OPTION_VALIDATED"
    RISK_APPROVED = "RISK_APPROVED"
    ENTRY_PENDING = "ENTRY_PENDING"
    OPEN = "OPEN"
    STOP_LOSS = "STOP_LOSS"
    T1_REACHED = "T1_REACHED"
    T2_REACHED = "T2_REACHED"
    T3_REACHED = "T3_REACHED"
    THESIS_INVALIDATION = "THESIS_INVALIDATION"
    TIME_EXIT = "TIME_EXIT"
    DATA_RECOVERY = "DATA_RECOVERY"
    FORCE_EXIT = "FORCE_EXIT"
    CLOSED = "CLOSED"
    RECONCILED = "RECONCILED"
    SESSION_END = "SESSION_END"

class PositionStatus(Enum):
    NO_POSITION = "NO_POSITION"
    SIGNAL_DETECTED = "SIGNAL_DETECTED"
    TRADE_VALIDATED = "TRADE_VALIDATED"
    ENTRY_PENDING = "ENTRY_PENDING"
    OPEN = "OPEN"
    T1_REACHED = "T1_REACHED"
    T2_REACHED = "T2_REACHED"
    T3_REACHED = "T3_REACHED"
    EXIT_PENDING = "EXIT_PENDING"
    CLOSED = "CLOSED"
    ENTRY_REJECTED = "ENTRY_REJECTED"
    DATA_DEGRADED = "DATA_DEGRADED"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"
    ORPHANED = "ORPHANED"

class ExitReason(Enum):
    TARGET_T1 = "TARGET_T1"
    TARGET_T2 = "TARGET_T2"
    TARGET_T3 = "TARGET_T3"
    STOP_LOSS = "STOP_LOSS"
    THESIS_INVALIDATION = "THESIS_INVALIDATION"
    TIME_EXIT = "TIME_EXIT"
    SESSION_EXIT = "SESSION_EXIT"
    DATA_FAILURE_EXIT = "DATA_FAILURE_EXIT"
    RISK_EXIT = "RISK_EXIT"
    MANUAL_EMERGENCY_EXIT = "MANUAL_EMERGENCY_EXIT"
    FORCE_EXIT = "FORCE_EXIT"

class DecisionType(Enum):
    TRADE = "TRADE"
    NO_TRADE = "NO_TRADE"
    WAIT = "WAIT"
    DATA_UNAVAILABLE = "DATA_UNAVAILABLE"
    DATA_DEGRADED = "DATA_DEGRADED"
    INVALID = "INVALID"
    DUPLICATE = "DUPLICATE"
    RECOVERY = "RECOVERY"

class DataQuality(Enum):
    LIVE = "LIVE"
    STALE = "STALE"
    DELAYED = "DELAYED"
    MISSING = "MISSING"
    INVALID = "INVALID"
    UNAVAILABLE = "UNAVAILABLE"

class Regime(Enum):
    STRONG_BULLISH = "STRONG_BULLISH"
    BULLISH = "BULLISH"
    NEUTRAL = "NEUTRAL"
    BEARISH = "BEARISH"
    STRONG_BEARISH = "STRONG_BEARISH"
    HIGH_VOLATILITY = "HIGH_VOLATILITY"
    UNSTABLE = "UNSTABLE"

class SetupType(Enum):
    BREAKOUT = "BREAKOUT"
    BREAKDOWN = "BREAKDOWN"
    TREND_CONTINUATION = "TREND_CONTINUATION"
    PULLBACK_CONTINUATION = "PULLBACK_CONTINUATION"
    SUPPORT_REVERSAL = "SUPPORT_REVERSAL"
    RESISTANCE_REJECTION = "RESISTANCE_REJECTION"
    MOMENTUM_EXPANSION = "MOMENTUM_EXPANSION"
    NO_SETUP = "NO_SETUP"

# Trading Constants
LOT_SIZES = {
    "NIFTY": 65,
    "SENSEX": 20,
    "BANKNIFTY": 25,
    "FINNIFTY": 40
}

# Target percentages based on DEPLOYED CAPITAL
TARGETS = {
    "T1": 0.15,
    "T2": 0.30,
    "T3": 0.50
}

STOP_LOSS_PCT = 0.05

# Exchange types for WebSocket
EXCHANGE_TYPES = {
    "NSE": 1,
    "NFO": 2,
    "BSE": 3,
    "BFO": 4,
    "MCX": 5
}

MODE_TYPES = {
    "LTP": 1,
    "QUOTE": 2,
    "SNAP_QUOTE": 3
}

INDEX_TOKENS = {
    "NIFTY": "9999",
    "SENSEX": "9998"
}

CERTIFICATION = {
    "NIFTY_REQUIRED": 100,
    "SENSEX_REQUIRED": 100,
    "COUNTABLE_TYPES": ["TRADE"],
    "NON_COUNTABLE_TYPES": ["NO_TRADE", "WAIT", "DATA_UNAVAILABLE", "DATA_DEGRADED", "INVALID", "DUPLICATE", "RECOVERY"]
}

MARKET_HOURS = {
    "OPEN": (9, 15),
    "CLOSE": (15, 30),
    "PRE_MARKET_START": (8, 0),
    "WARMUP_MINUTES": 15,
    "STOP_NEW_ENTRIES_MINUTES": 15
}

DATA_FRESHNESS = {
    "LTP": 2,
    "OPTION": 2,
    "QUOTE": 1,
    "SNAP_QUOTE": 1
}
