"""Initial deterministic paper-only technical policy."""
from __future__ import annotations
from dataclasses import dataclass
import math
_T=("5m","15m","1h","1d");_C=("TREND","MOMENTUM","VOLATILITY","VOLUME","LEVELS","PATTERNS")
@dataclass(frozen=True,slots=True)
class TechnicalIntelligencePolicyV1:
 policy_name:str;required_timeframes:tuple[str,...];rsi_period:int;ema_fast_period:int;ema_slow_period:int;macd_fast_period:int;macd_slow_period:int;macd_signal_period:int;adx_period:int;atr_period:int;bollinger_period:int;bollinger_stddev:float;volume_lookback:int;support_resistance_lookback:int;rsi_overbought:float;rsi_oversold:float;adx_threshold:float;category_weights:tuple[tuple[str,float],...];timeframe_weights:tuple[tuple[str,float],...];insufficient_history_behavior:str="BLOCK";unavailable_behavior:str="WARN";malformed_behavior:str="BLOCK";execution_mode:str="PAPER";live_execution_eligible:bool=False;schema_version:str="technical_intelligence_policy.v1";incomplete_timeframe_behavior:str="BLOCK";conflicting_timeframe_behavior:str="WARN"
 def __post_init__(self):
  cw,tw=tuple(self.category_weights),tuple(self.timeframe_weights);ns=(self.rsi_period,self.ema_fast_period,self.ema_slow_period,self.macd_fast_period,self.macd_slow_period,self.macd_signal_period,self.adx_period,self.atr_period,self.bollinger_period,self.volume_lookback,self.support_resistance_lookback)
  if (not self.policy_name or self.required_timeframes!=_T or any(not isinstance(v,int) or isinstance(v,bool) or v<=0 for v in ns) or ns!=(14,20,50,12,26,9,14,14,20,20,20) or (self.bollinger_stddev,self.rsi_overbought,self.rsi_oversold,self.adx_threshold)!=(2.0,70,30,25) or {k for k,_ in cw}!=set(_C) or tuple(k for k,_ in tw)!=_T or len(cw)!=6 or len(tw)!=4 or any(isinstance(v,bool) or not isinstance(v,(int,float)) or not math.isfinite(v) or v<0 for _,v in cw+tw) or not math.isclose(sum(v for _,v in cw),1.,abs_tol=1e-12) or not math.isclose(sum(v for _,v in tw),1.,abs_tol=1e-12) or any(v not in {"BLOCK","WARN","ALLOW"} for v in (self.insufficient_history_behavior,self.unavailable_behavior,self.malformed_behavior,self.incomplete_timeframe_behavior,self.conflicting_timeframe_behavior)) or self.execution_mode!="PAPER" or self.live_execution_eligible is not False or self.schema_version!="technical_intelligence_policy.v1"):raise ValueError("Invalid technical intelligence policy.")
  object.__setattr__(self,"category_weights",cw);object.__setattr__(self,"timeframe_weights",tw)
DEFAULT_TECHNICAL_INTELLIGENCE_POLICY=TechnicalIntelligencePolicyV1("INITIAL_CANONICAL_TECHNICAL_POLICY",_T,14,20,50,12,26,9,14,14,20,2.,20,20,70,30,25,(("TREND",.25),("MOMENTUM",.2),("VOLATILITY",.15),("VOLUME",.15),("LEVELS",.15),("PATTERNS",.1)),(("5m",.35),("15m",.3),("1h",.2),("1d",.15)))
